# This file is automatically generated. Do not edit.

if Object.const_defined?('TestFlight') and !UIDevice.currentDevice.model.include?('Simulator')
  NSNotificationCenter.defaultCenter.addObserverForName(UIApplicationDidBecomeActiveNotification, object:nil, queue:nil, usingBlock:lambda do |notification|
  
  TestFlight.takeOff('c0dbf67dff4b56cdbd8dd77258396000_MjcwMTUyMjAxMy0wOS0wOSAxMDo0MToxNC42NzU3MTA')
  end)
end
