# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Squash Charlotte'
  app.device_family          = [:iphone]
  app.interface_orientations = [:landscape_left]
  app.vendor_project( "vendor/cocos2d-iphone", :xcode,
    :xcodeproj => "cocos2d-ios.xcodeproj", :target => "cocos2d", :products => ["libcocos2d.a"],
    :headers_dir => "cocos2d")
  app.vendor_project  'vendor/cocos2d-iphone/CocosDenshion/CocosDenshion', :static
  app.frameworks += ["OpenGLES", "OpenAL", "AVFoundation", "AudioToolbox", "QuartzCore"]
  app.libs << "/usr/lib/libz.dylib"
end
